name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download ngrok
        run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.zip

      - name: Extract ngrok
        run: unzip ngrok.zip

      - name: Install unzip (if not already installed)
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Auth ngrok
        run: ./ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create Tunnel
        run: ./ngrok tcp 3389
